travis:
  secure:
    BINSTAR_TOKEN: eWsDxoMPP3Wf6I0RZhsuaIOMWYT6cn7PxcZ24mNRMhOraJcW8hnZZW3dVypj5zOqsp8VUkn86N0/LliZDPEfRccaVNFiBPNgtLPyYM3me9u5WZCQXaiu0H6KFQXN2ifRRNFqFrkp+FZizOjCb72XtPG/DNanKCZ5uLtO43YFxniJV1MtXH9vDwAbD5IWe3K2QRG4ZhwSF7c1BqKnrGpYwf875C3XgQNEkY6WAiySwWdiPwnuOD7cNsxzlicZg1EyHnTAG/e1EkFybdfRLfAalWSY62zq66lDcoGFLvbUgYE2VVknMKG3JpzpFJVJkSXa9HkQOTIRR/HybIo8mB/gTsFoED0zgO1LwCcWrCJmLHyvhDNNGJghmyrLHHZf8EwwIgr9N20dspF9xXgJNXEqD1HpzGr5naJeVZbDN2eKijaeD+v1q2bWrAvrXRdtUmvcOWJmc+nnwoU8y6pBc1oyoEao+do1taYBuuINbJcAAvq0f24ww29m7o41MFc+kwdn8hppPbxnFFzx9umcX4uc4VRcXD0dlLXESmxVmToau10MSPCDos5oMz91ktrREH6Fs/Xq9UA+8CaHeD2cCsYJ6LDL6/A1zAvl5Cs31R83ITPm8A3XSddlXOh7xwlTJ2c8Lxk+JC8SZiMBjMxaVlep0e3PDXhM0+sgHceGRyFUfRI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
